INSERT INTO pokemons (image_url, name, height, weight, type) VALUES
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', 'bulbasaur', 7, 69, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', 'ivysaur', 10, 130, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', 'venusaur', 20, 1000, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'charmander', 6, 85, 'fire'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', 'charmeleon', 11, 190, 'fire'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', 'charizard', 17, 905, 'fire, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', 'squirtle', 5, 90, 'water'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', 'wartortle', 10, 225, 'water'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', 'blastoise', 16, 855, 'water'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', 'caterpie', 3, 29, 'bug'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', 'metapod', 7, 99, 'bug'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', 'butterfree', 11, 320, 'bug, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', 'weedle', 3, 32, 'bug, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', 'kakuna', 6, 100, 'bug, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', 'beedrill', 10, 295, 'bug, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', 'pidgey', 3, 18, 'normal, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', 'pidgeotto', 11, 300, 'normal, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', 'pidgeot', 15, 395, 'normal, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', 'rattata', 3, 35, 'normal'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', 'raticate', 7, 185, 'normal'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', 'spearow', 3, 20, 'normal, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', 'fearow', 12, 380, 'normal, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', 'ekans', 20, 69, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', 'arbok', 35, 650, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'pikachu', 4, 60, 'electric'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png', 'raichu', 8, 300, 'electric'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png', 'sandshrew', 6, 120, 'ground'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png', 'sandslash', 10, 295, 'ground'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', 'nidoran-f', 4, 70, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', 'nidorina', 8, 200, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', 'nidoqueen', 13, 600, 'poison, ground'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', 'nidoran-m', 5, 90, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', 'nidorino', 9, 195, 'poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png', 'nidoking', 14, 620, 'poison, ground'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png', 'clefairy', 6, 75, 'fairy'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png', 'clefable', 13, 400, 'fairy'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', 'vulpix', 6, 99, 'fire'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', 'ninetales', 11, 199, 'fire'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png', 'jigglypuff', 5, 55, 'normal, fairy'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png', 'wigglytuff', 10, 120, 'normal, fairy'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png', 'zubat', 8, 75, 'poison, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png', 'golbat', 16, 550, 'poison, flying'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png', 'oddish', 5, 54, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png', 'gloom', 8, 86, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png', 'vileplume', 12, 186, 'grass, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png', 'paras', 3, 54, 'bug, grass'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png', 'parasect', 10, 295, 'bug, grass'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png', 'venonat', 10, 300, 'bug, poison'),
('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png', 'venomoth', 15, 125, 'bug, poison');
